name: Install dependencies
inputs:
  arch:
    description: Architecture
    required: true
  qt:
    description: Qt Version
    required: true
runs:
  using: composite
  steps:
  - if: runner.os == 'Windows'
    uses: jurplel/install-qt-action@v4
    with:
      arch: ${{inputs.arch}}
      version: ${{matrix.qt == 6 && '6.5.3' || '5.15.2'}}
      modules: ${{matrix.qt == 6 && 'qtmultimedia' || ''}}
  - if: runner.os == 'macOS' && inputs.qt == '6'
    uses: jurplel/install-qt-action@v3
    with:
      arch: clang_64
      version: '6.5.3'
      modules: 'qtmultimedia'
  - run: ${GITHUB_ACTION_PATH}/install-dependencies.sh
    shell: bash
    env:
      RUNNER_OS: ${{runner.os}}
      INPUT_ARCH: ${{inputs.arch}}
      INPUT_QT: ${{inputs.qt}}
