name: Install dependencies
inputs:
  arch:
    description: Architecture
    required: true
runs:
  using: composite
  steps:
  - run: ${GITHUB_ACTION_PATH}/install-dependencies.sh
    shell: bash
    env:
      RUNNER_OS: ${{runner.os}}
      INPUT_ARCH: ${{inputs.arch}}
