######################################################################
# Automatically generated by qmake (2.01a) sam. janv. 13 17:20:35 2007
######################################################################

TEMPLATE = subdirs
SUBDIRS = \
        core_lib \
        app \
        tests \
        3rdlib/quazip \
        3rdlib/zlib

app.depends = core_lib
tests.depends = core_lib
core_lib.depends = 3rdlib/quazip
3rdlib/quazip.depends = 3rdlib/zlib

