name: Set up environment
inputs:
  arch:
    description: Architecture
    required: true
  vcvars:
    description: Visual Studio architecture (Windows only)
    required: false
runs:
  using: composite
  steps:
  - name: Setup MSVC (Windows only)
    if: runner.os == 'Windows'
    uses: ilammy/msvc-dev-cmd@v1
    with:
      arch: ${{ inputs.vcvars }}
  - run: ${GITHUB_ACTION_PATH}/setup-environment.sh
    shell: bash
    env:
      RUNNER_OS: ${{runner.os}}
      INPUT_ARCH: ${{inputs.arch}}
  - run: ${GITHUB_ACTION_PATH}/setup-versions.sh
    shell: bash
