#ifndef CAMERAEASINGTYPE_H
#define CAMERAEASINGTYPE_H

enum class CameraEasingType {
    LINEAR,
    INQUAD,
    OUTQUAD,
    INOUTQUAD,
    OUTINQUAD,
    INCUBIC,
    OUTCUBIC,
    INOUTCUBIC,
    OUTINCUBIC,
    INQUART,
    OUTQUART,
    INOUTQUART,
    OUTINQUART,
    INQUINT,
    OUTQUINT,
    INOUTQUINT,
    OUTINQUINT,
    INCIRC,
    OUTCIRC,
    INOUTCIRC,
    OUTINCIRC
};

#endif // CAMERAEASINGTYPE_H
