#ifndef CAMERAFIELDOPTION_H
#define CAMERAFIELDOPTION_H

enum class CameraFieldOption {
    RESET_FIELD,
    RESET_TRANSITION,
    RESET_SCALING,
    RESET_ROTATION,
    RESET_HORIZONTAL,
    RESET_VERTICAL,
    HOLD_FRAME,
    SHOW_CAMERA_PATH
};

#endif // CAMERAFIELDOPTION_H
