/* src/ming_config.h.  Generated by configure.  */

#define USE_ZLIB 1
#define USE_GIF 0
#define USE_PNG 1

/*
 * Define this if you want Ming to track
 * all objects allocations. Ming will
 * mantain a linked doubly linked list
 * of allocated objects, call Ming_collectGarbage()
 * to get rid of them all.
 */
#define TRACK_ALLOCS 1

