!define MULTIUSER_EXECUTIONLEVEL Highest
!define MULTIUSER_MUI
!define MULTIUSER_INSTALLMODE_COMMANDLINE
!define MULTIUSER_INSTALLMODE_DEFAULT_REGISTRY_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${REGNAME}"
!define MULTIUSER_INSTALLMODE_DEFAULT_REGISTRY_VALUENAME "DisplayName"
!define MULTIUSER_INSTALLMODE_INSTDIR "${NAME}"
!if ${BITS} = 64
  !define MULTIUSER_USE_PROGRAMFILES64
!endif

!include MultiUser.nsh
